### ISSUE TITLE
おい！

### ISSUE THREAD

**Issue by kyu099** [TrpFrog/trpfrog.net#2]
## 誤りの内容
メンバー紹介の淵野アタリのTwitterリンクがkyu_099になってますアホ

## URL
https://trpfrog.net/blog/entry/haneda-tokyo-tower

**Comment by TrpFrog** [comment]
すごい！

**Comment by TrpFrog** [comment]
https://github.com/TrpFrog/trpfrog.net/commit/c01300e228c167c67b01c7a6f2a074fd6b807df7 で対応しました
