### ISSUE TITLE
トップページの文字背景色が怪しい

### ISSUE THREAD

**Issue by sushi-chaaaan** [trpfrog/trpfrog.net#65]
## 内容の説明
About Me内の文字の背景色が怪レいです

## URL
トップページなので省略します

## 環境
iOS17.3.1 iPhone15Pro
Safari ダークテーマ

## 詳しい説明
![image](https://github.com/trpfrog/trpfrog.net/assets/71284054/e1a8a7db-88b6-4cba-aca7-48655c4a2691)

**Comment by sushi-chaaaan** [comment]
再読み込みしたら治りました 桜の木の下に埋まります

**Comment by trpfrog** [comment]
デプロイした**直後に**嫌な予感がして確認したら色が壊れてたので即修正しちゃいました

報告ありがとうございます！ 𝑾𝑰𝑻𝑯 𝑩𝑰𝑮 𝑳𝑶𝑽𝑬……
